# 1) Implement Perceptron training algorithm to classify flowers in IRIS dataset.

In [ ]:
# Importing Packages
import matplotlib.pyplot as plt
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [ ]:
# Fetching data from the Iris Dataset
data=datasets.load_iris()
print(data)
x=data.data
y=data.target
z=data.target_names
print(data.feature_names)
print(x[0])

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
# Buliding model and Spliting the data into Train and Test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.5)
print(x_train.shape)
print(x_test.shape)
model = Sequential()
model.add(Dense(100,input_dim=(4),activation="relu"))
model.add(Dense(3,activation="softmax"))
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model.fit(x_train,y_train,epochs=20)
model.evaluate(x_test,y_test)
pred = model.predict(x_test[:10])
print(pred)
p=np.argmax(pred,axis=1)
print(p)
print(y_test[:10])
for i in p:
  print("Predicted class : {} , Name : {}".format(i,x[i]))

(75, 4)
(75, 4)
Epoch 1/20
3/3 [==============================] - 0s 5ms/step - loss: 1.3283 - accuracy: 0.5067
Epoch 2/20
3/3 [==============================] - 0s 4ms/step - loss: 1.2264 - accuracy: 0.6800
Epoch 3/20
3/3 [==============================] - 0s 4ms/step - loss: 1.1341 - accuracy: 0.7200
Epoch 4/20
3/3 [==============================] - 0s 4ms/step - loss: 1.0646 - accuracy: 0.7200
Epoch 5/20
3/3 [==============================] - 0s 3ms/step - loss: 1.0078 - accuracy: 0.7200
Epoch 6/20
3/3 [==============================] - 0s 3ms/step - loss: 0.9631 - accuracy: 0.7200
Epoch 7/20
3/3 [==============================] - 0s 4ms/step - loss: 0.9375 - accuracy: 0.7200
Epoch 8/20
3/3 [==============================] - 0s 5ms/step - loss: 0.9077 - accuracy: 0.7200
Epoch 9/20
3/3 [==============================] - 0s 4ms/step - loss: 0.8800 - accuracy: 0.7200
Epoch 10/20
3/3 [==============================] - 0s 4ms/step - loss: 0.8533 - accuracy: 0.7200
Epoch 11/20
3/3 [======

3/3 [==============================] - 0s 5ms/step - loss: 0.7038 - accuracy: 0.6267


1/1 [==============================] - 0s 42ms/step
[[0.11231302 0.25463733 0.63304955]
 [0.1001609  0.24346106 0.656378  ]
 [0.09511673 0.23509052 0.6697927 ]
 [0.1260132  0.27093914 0.6030476 ]
 [0.14556508 0.28539792 0.569037  ]
 [0.11522482 0.2625187  0.62225646]
 [0.19278546 0.31904915 0.48816532]
 [0.10856479 0.24664496 0.6447903 ]
 [0.1873937  0.30468985 0.50791645]
 [0.70363426 0.21643841 0.07992729]]
[2 2 2 2 2 2 2 2 2 0]
[2 2 2 2 2 2 1 2 1 0]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 2 , Name : [4.7 3.2 1.3 0.2]
Predicted class : 0 , Name : [5.1 3.5 1.4 0.2]
